config/routes.rb
Rails.application.routes.draw do
  root "tasks#calendar"
  resources :tasks do
    collection do
      get 'calendar'
      get 'bookmark'
    end
  end
  resources :clients, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :type_of_tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :image_authentications, only:[:create]
  resources :users, only: [:new, :create, :edit, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :instructions, only: [:index]
  namespace :admin do
    resources :users, only: [:index]
  end
  post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  post 'users/guest_admin_sign_in', to: 'sessions#guest_admin_sign_in'
end

app/models/task.rb
class Task < ApplicationRecord
  # clientとworking_processはnilでもOK
  belongs_to :client, optional: true
  belongs_to :user

  has_many :working_processes, dependent: :destroy  # タスクが削除されたら、付随する工程も削除する
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  validates :title, presence: true
  validates :note, length: { maximum: 140 }

  # 画像
  mount_uploader :image, ImageUploader

  # ソート
  scope :default, -> { order(created_at: :desc) }

  # シンプルカレンダー
  def start_time
    self.deadline_on #simple_calendarに表示させる日付のカラムを指定
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy] 
  before_action :back_to_index, only: [:edit, :update, :destroy]

  def index
    @tasks = Task.all.default

    if params[:bookmarks]
      bookmarks = Bookmark.where(user_id: current_user.id).pluck(:task_id)
      @tasks = Task.find(bookmarks)
    end
  end

  def calendar
     @tasks = Task.all
  end

  def bookmark
    bookmarks = Bookmark.where(user_id: current_user.id).pluck(:task_id)
    @tasks = Task.find(bookmarks)
  end

  def new
    if params[:back]
      set_task_form
    else
      @task_form = TaskForm.new(current_user)
    end
  end
  
  def create
    set_task_form
    if @task_form.save
      # msg：タスクを作成しました
      redirect_to task_path(@task_form.task), notice: t('notice.task_create')
    else
      render :new
    end
  end

  def show
    @working_processes = WorkingProcess.where('task_id = ?', @task.id)
    @bookmark = current_user.bookmarks.find_by(task_id: @task.id)
    # binding.pry
  end

  def edit
    @task_form = TaskForm.new(current_user)
    task_form_params
  end

  def update
    set_task_form
    task_form_params
    if @task_form.update(current_user, task_params)
      # msg：タスクを更新しました
      redirect_to task_path(@task), notice: t('notice.task_update')
    else
      render :edit
    end
  end

  def destroy
    @working_processes = WorkingProcess.where('task_id = ?', @task.id)
    @working_processes.each do | working_process |
      working_process.destroy
    end
    @task.destroy
    # msg：タスクを削除しました
    redirect_to tasks_path, notice: t('danger.task_delete')
  end

  private

  def set_task_form
    @task_form = TaskForm.new(current_user, task_params)
  end

  def task_params
    params.require(:task).permit(
      :title, 
      :note, 
      :deadline_on, 
      :done, 
      :client_id, 
      :image, 
      :image_cache,
      clients: [
        :id,
        :name],
      type_of_tasks: [
        :id,
        :name],
      working_process: [
        :type_of_task_id, 
        :workload, 
        :working_hour, 
        :unit,
        :task_id,
        :_destroy
      ])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_form_params
    @task_form.task = @task
    @task_form.client = @task.client
    @working_processes = WorkingProcess.where('task_id = ?', @task.id)
    unless @working_processes.count.zero?
      @task_form.type_of_task = @working_processes.first.type_of_task
      # 複数登録できるように変更予定
      @task_form.working_process = @working_processes.first
    end
  end

  def back_to_index
    # 自分以外のユーザーが編集・削除しようとするとタスク一覧画面に遷移
     if current_user != @task.user
      redirect_to tasks_path
     end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == "create"
      tasks_path
    elsif action_name == "edit"
      task_path
    end
  end

  def redirect
    before_uri = URI.parse(request.referer)
    path = Rails.application.routes.recognize_path(before_uri.path)
    # もし直前のアクションがindex、bookmark、calendarだったら
    # 各アクションへのパスを指定。それ以外の場合はカレンダーへ戻る
    valid_actions = ["index", "bookmark", "calendar"]
    return path if valid_actions.include?(path[:action])
    calendar_tasks_path
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task_form.task, local: true, url: choose_new_or_edit) do |form| %>
  <% if @task_form.task.errors.any? %>
    <div id="error_explanation" class = "text-danger">
      <!--<h2><%= @task_form.task.errors.count %>件のエラーがあります。</h2>-->
      <ul>
      <% @task_form.task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# 画像認証機能 %>
  <%= javascript_pack_tag 'tasks/_form' %>
  <!-- テーブル作成 -->
  <table>
    <tr><!-- 画像 -->
      <td colspan="2" class = "task_key text-black-50">
        <%= form.label :image %><br>
        <%= form.file_field :image, capture: "environment", accept: "image/*", class: "image_size_default" %>
      </td>
    </tr>
    <tr><!-- タスクのタイトル -->
      <td class = "center">
      <!-- <%= form.label :done, class: "task_key text-black-50" %><br> -->
        <%= form.check_box :done %>
      </td>
      <td>
        <%= form.label :title, class: "task_key text-black-50" %><br>
        <%= form.text_field :title, class: "text_area task_value" %>
      </td>
    </tr>
    <tr><!-- メモ -->
      <td colspan="2">
        <%= form.label :note, class: "task_key text-black-50" %><br>
        <%= form.text_area :note, class: "text_area  task_value"%>
      </td>
    </tr>
    <tr><!-- 納期 -->
      <td colspan="2">
        <%= form.label :deadline_on, class: "task_key text-black-50" %><br>
        <%= form.date_field :deadline_on %></td>
    </tr>
    <!---------- 編集時 ---------->
    <%if @task_form.task.id %>
    <tr><!-- 取引先 -->
      <td colspan="2">
        <div class = "task_key text-black-50"><%= t('task_form.crient.name') %></div>
        <%= text_field_tag 'task[clients][name]',  @task_form.client&.name, class: "text_area  task_value" %>
      </td>
    </tr>
    <tr><!-- 作業工程 -->
      <td colspan="2">
        <div class = "task_key text-black-50"><%= t('task_form.type_of_task.name') %></div>
        <%= text_field_tag 'task[type_of_tasks][name]',  @task_form.type_of_task&.name, class: "text_area  task_value" %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <!-- 作業量 -->
        <div class = "working_process_side">
          <div>
            <div class = "task_key text-black-50"><%= t('task_form.working_process.workload') %></div>
            <%= number_field_tag 'task[working_process][workload]',  @task_form.working_process&.workload, class: "text_area task_value_short" %>
          </div>
          <!-- 作業時間 -->
          <div>
            <div class = "task_key text-black-50"><%= t('task_form.working_process.working_hour') %></div>
            <%= number_field_tag 'task[working_process][working_hour]',  @task_form.working_process&.working_hour, class: "text_area task_value_short" %>
          </div>
          <div class = "time_unit">
            <%= select_tag 'task[working_process][unit]',  options_for_select(WorkingProcess.units_i18n.invert, @task_form.working_process&.unit) %>
          </div>
        </div>
      </td>
    </tr>
    <% else %>
    <!---------- 新規作成時 ---------->
    <tr><!-- 取引先 -->
      <td colspan="2">
        <%= form.fields_for :clients do | clients_form | %>
          <div class = "task_key text-black-50"><%= t('task_form.crient.name') %></div>
          <%= clients_form.text_field :name, class: "text_area  task_value" %>
        <% end %>
      </td>
    </tr>
    <tr><!-- 作業工程 -->
      <td colspan="2">
        <%= form.fields_for :type_of_tasks do | type_of_tasks_form | %>
          <div class = "task_key text-black-50"><%= t('task_form.type_of_task.name') %></div>
          <%= type_of_tasks_form.text_field :name, class: "text_area  task_value" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= form.fields_for :working_process do | working_processes_form | %>
          <!-- 作業量 -->
          <div class = "working_process_side">
            <div>
              <div class = "task_key text-black-50"><%= t('task_form.working_process.workload') %></div>
              <%= working_processes_form.number_field :workload, class: "text_area task_value_short" %>
            <!-- 作業時間 -->
            </div>
            <div>
              <div class = "task_key text-black-50"><%= t('task_form.working_process.working_hour') %></div>
              <%= working_processes_form.number_field :working_hour, class: "text_area task_value_short" %>
            </div>
            <div class = "time_unit">
              <%= working_processes_form.select(:unit, WorkingProcess.units_i18n.invert, {}, include_blank: true) %> 
            </div>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>

  <div id="img_field">
    <% if @task_form.task.image.present? %>
      <%= image_tag(@task_form.task.image.url) %>
    <% else %>
      <i class="fas fa-images"></i>
    <% end %>
  </div>
  
   <div class = "center"><%= form.submit class: "btn btn-primary bottun" %></div>
<% end %>

app/views/tasks/bookmark.html.erb
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p>ブックマーク</p>
</div>
<ul>
  <% @tasks.each do | task | %>
    <li>
      <%= task.title %>｜
      <%= link_to '詳細', task_path(task.id) %>｜
      <%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除してよろしですか？'}, class: "text-danger" %>
    </li>
  <% end %>
</ul>

app/views/tasks/calendar.html.erb
<!-- メニュー -->
<div class="openbtn1"><span></span><span></span><span></span></div>
<nav id="g-nav">
  <div id="g-nav-list">
    <ul>
      <li><%= link_to "作業工程", type_of_tasks_path %></li>
      <li><%= link_to "取引先", clients_path %></li>
      <li><%= link_to "ブックマーク", bookmark_tasks_path %></li>
      <li><%= link_to "タスク一覧", tasks_path %></li>
      <% if current_user.admin? %>
        <li><%= link_to "ユーザー一覧", admin_users_path %></li>
      <% end %>
      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "text-danger" %></li>
    </ul>
  </div>
</nav>

<div class="page_title">
  <p>カレンダー</p>
</div>
<br>
<%= link_to '新規作成', new_task_path %><br>

<div class="icon_size_mini user_icon">
  <%= link_to image_tag(default_img(current_user.icon&.url)), user_path(current_user.id) %>
</div>
<br>

<div class="col-md-8">
<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date.day %>

  <% tasks.each do |task| %>
    <div>
      <%= link_to task.title, task %>
    </div>
  <% end %>
<% end %>



<%= javascript_pack_tag 'tasks/sidebar' %>

app/views/tasks/edit.html.erb
<%= link_to '<戻る', :back, class: "browser_back" %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>
<div class = "form_center">
  <%= render 'form' %>

  <div class = "center">
    <%= link_to '削除', task_path(@task.id), method: :delete ,data: { confirm: '本当に削除してよろしですか？'}, class: "btn btn-outline-danger bottun" %>
  </div>
</div>

app/views/tasks/index.html.erb
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>

<%= link_to '新規作成', new_task_path %><br>
<%= link_to 'お気に入りのみ表示', tasks_path(bookmarks: "true") %>

<ul>
  <% @tasks.each do | task | %>
    <li>
      <%= task.title %>｜
      <%= link_to '詳細', task_path(task.id) %>｜
      <%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除してよろしですか？'}, class: "text-danger" %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= link_to '<戻る', :back, class: "browser_back" %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>

<div class = "form_center">
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<%#= link_to '<戻る', redirect, class: "browser_back" %>
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>

<div class = "form_center task_show">
  <table>
    <!-- タイトル -->
    <tr>
      <td class = "task_show_td_icon center">
        <% if @task.done %>
          <div class = "text-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-square-fill" viewBox="0 0 16 16">
              <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 1 .011 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.75.75 0 0 1 1.08-.022z"/>
            </svg>
          </div>
        <% else %>
          <div class = "text-secondary center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
            </svg>
          </div>
        <% end %>
      </td>
      <td>
        <div class = "task_key text-black-50"><%= t('activerecord.attributes.task.title') %></div>
        <div class = "task_value" ><%= @task.title %></div>
      </td>
    </tr>
    <!-- メモ -->
    <tr>
      <td colspan="2">
        <div class = "task_key text-black-50"><%= t('activerecord.attributes.task.note') %></div>
        <div class = "task_value" ><%= @task.note %></div>
      </td>
    </tr>
    <!-- 納期 -->
    <tr>
      <td colspan="2">
        <div class = "task_key text-black-50"><%= t('activerecord.attributes.task.deadline_on') %></div>
        <div class = "task_value" ><%= @task.deadline_on %></div>
      </td>
    </tr>
    <!-- 取引先 -->
    <tr>
      <td colspan="2">
        <div class = "task_key text-black-50"><%= t('activerecord.attributes.client.name') %></div>
        <div class = "task_value" ><%= @task.client&.name %></div>
      </td>
    </tr>
    <!-- 作業工程 -->
    <% @working_processes.each do |process| %>

      <tr>
        <td colspan="2">
          <div class = "task_key text-black-50"><%= t('activerecord.attributes.task/type_of_tasks.name') %></div>
          <div class = "task_value" ><%= process.type_of_task&.name %></div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <!-- 作業量 -->
          <div class = "working_process_side">
            <div>
              <div class = "task_key text-black-50"><%= t('activerecord.attributes.working_process.workload') %></div>
              <div class = "task_value_short" ><%= process.workload %></div>
            </div>
            <div>
              <div class = "task_key text-black-50"><%= t('activerecord.attributes.working_process.working_hour') %></div>
              <div class = "task_value_short" ><%= process.working_hour %><%= process.unit %></div>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td class = "center task_show_td_icon" >
          <%# お気に入り %>
          <% if @bookmark.present? %>
              <%# 解除 %>
              <%= link_to bookmark_path(id: @bookmark.id), method: :delete, class: 'text-warning' do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
              <% end %>
            <% else %>
              <%# 登録 %>
              <%= link_to bookmarks_path(task_id: @task.id), method: :post, class: 'text-secondary' do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                </svg>
              <% end %>
          <% end %>
        </td>
        <td>
          <%= t('task_form.bookmark') %>
        </td>
      </tr>
      <% if @task.image.url %>
        <tr>
          <td>
            <div class = "task_value"><%= image_tag @task.image.url, class: 'image_size_default' %></p>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <div class = "center">
    <%= link_to '編集', edit_task_path, class: "btn btn-outline-primary bottun" %>
  </div>
</div>