config/routes.rb
Rails.application.routes.draw do
  root "tasks#calendar"
  resources :tasks do
    collection do
      get 'calendar'
      get 'bookmark'
    end
  end
  resources :clients, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :type_of_tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :image_authentications, only:[:create]
  resources :users, only: [:new, :create, :edit, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :instructions, only: [:index]
  namespace :admin do
    resources :users, only: [:index]
  end
  post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  post 'users/guest_admin_sign_in', to: 'sessions#guest_admin_sign_in'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  
  accepts_nested_attributes_for :tasks,
   allow_destroy: true

  validates :name, presence: true, length: { maximum: 30 }
  before_validation { email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }, on: :create

  mount_uploader :icon, ImageUploader

  enum roll: {
    general: 0,  # 一般
    admin: 1,    # 管理者
  }

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲスト（一般）"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
      user.name = "ゲスト（管理者）"
      user.roll = 1
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :exclude_general

  def index
    @users = User.all
  end

  private

  def exclude_general
    unless current_user.roll == 'admin'
      # msg；管理者以外はアクセスできません
      flash[:danger] = t('danger.only_administrators')
      redirect_to calendar_tasks_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :back_to_index, only: [:show, :edit, :update]

  def new
    return redirect_to calendar_tasks_path if logged_in?
    @user = User.new
    # @submit_text = "アカウント登録"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id   # ユーザー作成時にログイン
      redirect_to calendar_tasks_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @submit_text = "保存"
  end

  def update
    if @user.update(user_params)
      # msg：ユーザー情報を更新しました
      redirect_to user_path, notice: t('notice.user_update')
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :icon,
                                 :password_confirmation, :roll)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def back_to_index
    redirect_to tasks_path unless current_user == @user
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin?
    return false unless current_user.roll == 'admin'
    true
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def default_img(image)
    image.presence || 'icon.png'
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %> 
<% if action_name == "new"%>
  <div class="form_side add_pading_top">
    <div class = "form_center">
      <div class = "signin_frame user_form_center form_center">
<% else %>
  <div class="form_side">
    <div class = "form_center">
      <div class = "user_form_center form_center">
<% end %>
        <table>
          <tr>
            <td colspan="2">
              <div class="icon_size_default center">
                <%= image_tag default_img(@user.icon&.url)%>
              </div>
            </td>
          </tr>
          <tr> 
            <td colspan="2" class = "center">
              <%= f.file_field :icon, class: "icon_size_default icon_center" %>
            </td>
          </tr>
          <tr>
            <td><%= f.label :name %></td>
            <td><%= f.text_field :name, class: "text_area" %></td>
          </tr>
          <tr>
            <td><%= f.label :email %></td>
            <td><%= f.email_field :email, class: "text_area" %></td>
          </tr>
            <td><%= f.label :password %></td>
            <td><%= f.password_field :password, class: "text_area" %></td>
          </tr>
          <tr>
            <td><%= f.label :password_confirmation %></td>
            <td><%= f.password_field :password_confirmation, class: "text_area" %></td>
          </tr>
          <tr>
            <td><%= f.label :roll %></td>
            <td><%= f.select(:roll, User.rolls_i18n.invert, {}) %></td>
          </tr>
          <tr class = "center">
            <td colspan="2"><%= f.submit class: "btn btn-primary" %></td>
          </tr>
        </table>
        
      </div>
      <% if action_name == "new"%>
          <br><br>
          <%= link_to t('users.new.sign_in'), new_session_path %>
        <% end %>
    </div>
    </div>
    
    <% if @user.errors.any? %>
      <div class = "right_side text-danger">
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= link_to '<戻る', user_path(current_user.id) %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>
<%# <h1>ユーザ情報編集</h1> %>
<div class = "form_center">
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<%# <h1>ユーザ登録</h1> %>

  <%= render 'form' %>

app/views/users/show.html.erb
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p><%= t('.title') %></p>
</div>
<div class = "form_center">
  <div class = "user_form_center form_center center">
    <table>
      <tr>
        <td colspan="2">
          <div class="icon_size_default">
            <%= image_tag default_img(@user.icon&.url) %>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.name %></td>
      </tr>
      <tr>
        <td><%= t('activerecord.attributes.users.email') %></td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td colspan="2" class = "center"><%= link_to '編集', edit_user_path(@user.id), class: "btn btn-outline-primary" %></td>
      </tr>
    </table>
  </div>
</div>