config/routes.rb
Rails.application.routes.draw do
  root "tasks#calendar"
  resources :tasks do
    collection do
      get 'calendar'
      get 'bookmark'
    end
  end
  resources :clients, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :type_of_tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :image_authentications, only:[:create]
  resources :users, only: [:new, :create, :edit, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :instructions, only: [:index]
  namespace :admin do
    resources :users, only: [:index]
  end
  post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  post 'users/guest_admin_sign_in', to: 'sessions#guest_admin_sign_in'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :tasks, dependent: :destroy # 取引先が削除されたら、関連タスクも削除される

  before_save :check_and_save

  validates :name, uniqueness: true
  validates :name, presence: true

  private

  def check_and_save
    return false unless name_blank?
  end

  def name_blank?
    !self.name.blank?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy] 

  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: "取引先を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: "取引先情報を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: "取引先を削除しました"
  end

  private
  
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name)
  end
end

app/views/clients/_form.html.erb
<%= form_with(model: @client, local: true) do |form| %>

<% if @client.errors.any? %>
  <div id="error_explanation">
    <h2><%= @client.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div >
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
  <%= form.submit '保存', class: "btn btn-primary" %>
<% end %>

app/views/clients/edit.html.erb
<%= link_to '<戻る', clients_path, class: "browser_back" %>
<div class="page_title">
  <p>取引先 - 編集</p>
</div>

<%= render 'form' %>
<%= link_to '削除', client_path(@client.id), method: :delete ,data: { confirm: "#{@client.name}に関連するタスクも全て削除されます。\n本当に削除してよろしですか？"}, class: "btn btn-outline-danger" %>

app/views/clients/index.html.erb
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p>取引先 - 一覧</p>
</div>

<%= link_to '新規作成', new_client_path %>

<ul>
  <% @clients.each do | client | %>
    <li>
      <%= client.name %>｜
      <%= link_to '編集', edit_client_path(client.id) %>｜
      <%= link_to '削除', client_path(client.id), method: :delete ,data: { confirm: "#{client.name}に関連するタスクも全て削除されます。\n本当に削除してよろしですか？"}, class: "text-danger" %>
    </li>
  <% end %>
</ul>

app/views/clients/new.html.erb
<%= link_to '<戻る', clients_path, class: "browser_back" %>
<div class="page_title">
  <p>取引先 - 登録</p>
</div>

<%= render 'form' %>