config/routes.rb
Rails.application.routes.draw do
  root "tasks#calendar"
  resources :tasks do
    collection do
      get 'calendar'
      get 'bookmark'
    end
  end
  resources :clients, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :type_of_tasks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :image_authentications, only:[:create]
  resources :users, only: [:new, :create, :edit, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :instructions, only: [:index]
  namespace :admin do
    resources :users, only: [:index]
  end
  post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  post 'users/guest_admin_sign_in', to: 'sessions#guest_admin_sign_in'
end

app/models/type_of_task.rb
class TypeOfTask < ApplicationRecord
  has_many :working_processes, dependent: :destroy # 大元の工程が削除されたら、タスクに登録されている各工程も削除される

  before_save :check_and_save

  # 空欄不可、30文字以内、重複不可
  validates :name, presence: true, length: { maximum: 30 }
  validates :name, uniqueness: true

  private

  def check_and_save
    return false unless name_blank?
  end

  def name_blank?
    !self.name.blank?
  end
end

app/controllers/type_of_tasks_controller.rb
class TypeOfTasksController < ApplicationController
  before_action :set_type_of_task, only: [:show, :edit, :update, :destroy] 

  def index
    @type_of_tasks = TypeOfTask.all
  end

  def new
    @type_of_task = TypeOfTask.new
  end

  def create
    @type_of_task = TypeOfTask.new(type_of_task_params)
    if @type_of_task.save
      redirect_to type_of_tasks_path, notice: "作業工程を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @type_of_task.update(type_of_task_params)
      redirect_to type_of_tasks_path, notice: "作業工程情報を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @type_of_task.destroy
    redirect_to tasks_path, notice: "作業工程を削除しました"
  end

  private
  
  def set_type_of_task
    @type_of_task = TypeOfTask.find(params[:id])
  end

  def type_of_task_params
    params.require(:type_of_task).permit(:name,
      working_processes_attributes: [:id, :_destroy])
  end
end

app/views/type_of_tasks/_form.html.erb
<%= form_with(model: @type_of_task, local: true) do |form| %>

<% if @type_of_task.errors.any? %>
  <div id="error_explanation">
    <h2><%= @type_of_task.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @type_of_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div >
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
  <%= form.submit '保存', class: "btn btn-primary" %>
<% end %>

app/views/type_of_tasks/edit.html.erb
<%= link_to '<戻る', type_of_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p>作業工程 - 編集</p>
</div>

<%= render 'form' %>
<%= link_to '削除', type_of_task_path(@type_of_task.id), method: :delete ,data: { confirm: "タスクに登録されている工程も削除されます。\n本当に削除してよろしですか？"}, class: "btn btn-outline-danger" %>

app/views/type_of_tasks/index.html.erb
<%= link_to '<戻る', calendar_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p>作業工程 - 一覧</p>
</div>

<%= link_to '新規作成', new_type_of_task_path %>

<ul>
  <% @type_of_tasks.each do | type_of_task | %>
    <li>
      <%= type_of_task.name %>｜
      <%= link_to '編集', edit_type_of_task_path(type_of_task.id) %>｜
      <%= link_to '削除', type_of_task_path(type_of_task.id), method: :delete ,data: { confirm: "タスクに登録されている工程も削除されます。\n本当に削除してよろしですか？"}, class: "text-danger" %>
    </li>
  <% end %>
</ul>

app/views/type_of_tasks/new.html.erb
<%= link_to '<戻る', type_of_tasks_path, class: "browser_back" %>
<div class="page_title">
  <p>作業工程 - 登録</p>
</div>

<%= render 'form' %>